server:
  port: 9000

uri:
  context-path: /api
  resource-version: /v1
  domain: /sjdelacruz
  subdomain: /authentication-server
  endpoints:
    base-path: ${uri.context-path}${uri.resource-version}${uri.domain}${uri.subdomain}
    users: 
      profile: /profile

spring:
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true